### ISSUE TITLE
Upgrading to medic-nootils@3.x includes test-only dependencies

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-nootils#9]
**Problem:**
Webapp requires the medic-nootils npm package to provide the `Utils` function. This is used in a production system and all dependencies of the medic-nootils library end up in the webapp dependency tree.

Since medic-nootils has some dependencies like sinon, chai, nools, medic-conf which are for some test-only components in the same package, these dependencies are bloating the webapp and complicating the upgrade process.

**Proposed solution:**
We should fork the test-wrapper and test-utils classes into a separate npm package.  Or if these have been replaced by the medic-conf-test-harness, we can consider removing these in a new breaking change.

Scheduling this in 3.8 since upgrading to the latest medic-nootils is required for https://github.com/medic/medic/issues/5657.

**Comment by kennsippell** [comment]
@newtewt Interested in your thoughts on the best approach here.

**Comment by newtewt** [comment]
@kennsippell  I'm personally of the mind set we should not affect prod code or upgrading process because of testing requirements. I also like having all of our testing functionality in one place while also allowing the consumer to require only what they need.

**Comment by garethbowen** [comment]
@kennsippell This is in the Done column but not closed - can it be closed off now?

**Comment by kennsippell** [comment]
Yep!
